[package]
name = "match3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9"
rand = "0.8.5"
queues = "1.1.0"
bevy_match3 = "*"